export default {
  UPPER_BOUNDARY: 0,
  LEFT_BOUNDARY: 0,
  RIGHT_BOUNDARY: 900,
  LOWER_BOUNDARY: 400,
  COLORS: ["#00b6d3", "red", "green", "magenta"],
  MIN_DENSITY: 10,
  MAX_DENSITY: 100,
  MIN_SPEED: 1,
  MAX_SPEED: 2,
  MIN_RADIUS: 8,
  MAX_RAIDUS: 16,
};
